//! Deterministic, data-only renderer used by the syntax crate build script.

use std::collections::{BTreeMap, BTreeSet, VecDeque};
use ungrammar::{Grammar, Node, Rule, Token};

const MARKER: &str = "// @generated by crates/allen-syntax/build.rs; DO NOT EDIT.\n";
const GRAMMAR_FENCE_HEADER: &str = "#### Grammar\n\n```text\n";
const AST_PRELUDE: &str = r#"use crate::{AllenLanguage, SyntaxElement, SyntaxNode, SyntaxToken};
use rowan::ast::{support, AstChildren, AstNode};
use std::collections::{BTreeMap, BTreeSet, VecDeque};
use std::rc::Rc;

/// Recovery structure retained directly beneath a typed AST wrapper.
#[derive(Clone, Debug, Eq, Hash, PartialEq)]
pub enum AstError {
    Error(SyntaxNode),
    Missing(SyntaxNode),
    ErrorToken(SyntaxToken),
}

impl AstError {
    fn cast(element: SyntaxElement) -> Option<Self> {
        match element {
            rowan::NodeOrToken::Node(node) if node.kind() == SyntaxKind::Error => Some(Self::Error(node)),
            rowan::NodeOrToken::Node(node) if node.kind() == SyntaxKind::Missing => Some(Self::Missing(node)),
            rowan::NodeOrToken::Token(token) if token.kind() == SyntaxKind::ErrorToken => Some(Self::ErrorToken(token)),
            _ => None,
        }
    }

    #[must_use]
    pub fn kind(&self) -> SyntaxKind {
        match self {
            Self::Error(node) | Self::Missing(node) => node.kind(),
            Self::ErrorToken(token) => token.kind(),
        }
    }
}

#[derive(Clone, Copy)]
enum AstPattern {
    Atom { kind: SyntaxKind, label: Option<u16> },
    Seq(&'static [AstPattern]),
    Alt(&'static [AstPattern]),
    Opt(&'static AstPattern),
    Rep(&'static AstPattern),
}

#[derive(Clone, Debug)]
struct AstCapture {
    previous: Option<Rc<Self>>,
    element: Option<SyntaxElement>,
}

#[derive(Clone, Debug)]
struct AstMatch {
    pos: usize,
    score: usize,
    field_count: usize,
    fields: Option<Rc<AstCapture>>,
}

fn ast_fields(node: &SyntaxNode, pattern: &AstPattern, label: u16) -> Vec<Option<SyntaxElement>> {
    ast_fields_with_work(node, pattern, label).0
}

fn ast_fields_with_work(
    node: &SyntaxNode,
    pattern: &AstPattern,
    label: u16,
) -> (Vec<Option<SyntaxElement>>, usize) {
    let elements = node
        .children_with_tokens()
        .filter(|element| {
            !matches!(
                element.kind(),
                SyntaxKind::Whitespace
                    | SyntaxKind::Newline
                    | SyntaxKind::LineComment
                    | SyntaxKind::BlockComment
                    | SyntaxKind::Error
                    | SyntaxKind::ErrorToken
            )
        })
        .collect::<Vec<_>>();
    let mut work = 0;
    let initial = AstMatch {
        pos: 0,
        score: 0,
        field_count: 0,
        fields: None,
    };
    let matches = if ast_has_nested_repetition(pattern, false) {
        ast_apply_automaton(pattern, &elements, initial, label, &mut work)
    } else {
        ast_apply(pattern, &elements, vec![initial], label, &mut work)
    };
    let fields = matches
        .into_iter()
        .max_by_key(|state| {
            (
                state.pos == elements.len(),
                state.pos,
                state.score,
                state.field_count,
            )
        })
        .map_or_else(Vec::new, ast_materialize_fields);
    (fields, work)
}

fn ast_materialize_fields(state: AstMatch) -> Vec<Option<SyntaxElement>> {
    let mut fields = Vec::with_capacity(state.field_count);
    let mut capture = state.fields;
    while let Some(current) = capture {
        fields.push(current.element.clone());
        capture = current.previous.clone();
    }
    fields.reverse();
    fields
}

fn ast_has_nested_repetition(pattern: &AstPattern, inside_repetition: bool) -> bool {
    match pattern {
        AstPattern::Rep(pattern) => {
            inside_repetition || ast_has_nested_repetition(pattern, true)
        }
        AstPattern::Opt(pattern) => ast_has_nested_repetition(pattern, inside_repetition),
        AstPattern::Seq(patterns) | AstPattern::Alt(patterns) => patterns
            .iter()
            .any(|pattern| ast_has_nested_repetition(pattern, inside_repetition)),
        AstPattern::Atom { .. } => false,
    }
}

#[derive(Clone, Copy)]
enum AstAutomatonEdge {
    Epsilon(usize),
    Atom {
        kind: SyntaxKind,
        label: Option<u16>,
        next: usize,
    },
}

struct AstAutomaton {
    edges: Vec<Vec<AstAutomatonEdge>>,
    start: usize,
    accept: usize,
}

impl AstAutomaton {
    fn compile(pattern: &AstPattern) -> Self {
        let mut automaton = Self {
            edges: Vec::new(),
            start: 0,
            accept: 0,
        };
        let (start, accept) = automaton.fragment(pattern);
        automaton.start = start;
        automaton.accept = accept;
        automaton
    }

    fn state(&mut self) -> usize {
        let state = self.edges.len();
        self.edges.push(Vec::new());
        state
    }

    fn epsilon(&mut self, from: usize, to: usize) {
        self.edges[from].push(AstAutomatonEdge::Epsilon(to));
    }

    fn fragment(&mut self, pattern: &AstPattern) -> (usize, usize) {
        match pattern {
            AstPattern::Atom { kind, label } => {
                let start = self.state();
                let accept = self.state();
                self.edges[start].push(AstAutomatonEdge::Atom {
                    kind: *kind,
                    label: *label,
                    next: accept,
                });
                (start, accept)
            }
            AstPattern::Seq(patterns) => {
                let start = self.state();
                let mut tail = start;
                for pattern in *patterns {
                    let (next_start, next_accept) = self.fragment(pattern);
                    self.epsilon(tail, next_start);
                    tail = next_accept;
                }
                (start, tail)
            }
            AstPattern::Alt(patterns) => {
                let start = self.state();
                let accept = self.state();
                for pattern in *patterns {
                    let (branch_start, branch_accept) = self.fragment(pattern);
                    self.epsilon(start, branch_start);
                    self.epsilon(branch_accept, accept);
                }
                (start, accept)
            }
            AstPattern::Opt(pattern) => {
                let start = self.state();
                let accept = self.state();
                let (inner_start, inner_accept) = self.fragment(pattern);
                self.epsilon(start, accept);
                self.epsilon(start, inner_start);
                self.epsilon(inner_accept, accept);
                (start, accept)
            }
            AstPattern::Rep(pattern) => {
                let start = self.state();
                let accept = self.state();
                let (inner_start, inner_accept) = self.fragment(pattern);
                self.epsilon(start, accept);
                self.epsilon(start, inner_start);
                self.epsilon(inner_accept, inner_start);
                self.epsilon(inner_accept, accept);
                (start, accept)
            }
        }
    }
}

fn ast_apply_automaton(
    pattern: &AstPattern,
    elements: &[SyntaxElement],
    initial: AstMatch,
    selected_label: u16,
    work: &mut usize,
) -> Vec<AstMatch> {
    let automaton = AstAutomaton::compile(pattern);
    let mut current = BTreeMap::from([(automaton.start, initial)]);
    let mut matches = Vec::new();
    for position in 0..=elements.len() {
        ast_automaton_epsilon_closure(&automaton, &mut current, work);
        if let Some(state) = current.get(&automaton.accept) {
            matches.push(state.clone());
        }
        let Some(element) = elements.get(position) else {
            break;
        };
        let actual = element.kind();
        let mut next = BTreeMap::new();
        for (state, matched) in &current {
            for edge in &automaton.edges[*state] {
                let AstAutomatonEdge::Atom { kind, label, next: target } = edge else {
                    continue;
                };
                *work += 1;
                if actual != *kind && actual != SyntaxKind::Missing {
                    continue;
                }
                let mut candidate = matched.clone();
                candidate.pos = position + 1;
                candidate.score += usize::from(actual == *kind);
                if *label == Some(selected_label) {
                    candidate.field_count += 1;
                    candidate.fields = Some(Rc::new(AstCapture {
                        previous: candidate.fields,
                        element: (actual != SyntaxKind::Missing).then(|| element.clone()),
                    }));
                }
                ast_insert_automaton_state(&mut next, *target, candidate);
            }
        }
        current = next;
    }
    matches
}

fn ast_automaton_epsilon_closure(
    automaton: &AstAutomaton,
    states: &mut BTreeMap<usize, AstMatch>,
    work: &mut usize,
) {
    let mut pending = states.keys().copied().collect::<VecDeque<_>>();
    while let Some(state) = pending.pop_front() {
        let matched = states
            .get(&state)
            .expect("pending automaton state must have a match")
            .clone();
        for edge in &automaton.edges[state] {
            let AstAutomatonEdge::Epsilon(target) = edge else {
                continue;
            };
            *work += 1;
            if ast_insert_automaton_state(states, *target, matched.clone()) {
                pending.push_back(*target);
            }
        }
    }
}

fn ast_insert_automaton_state(
    states: &mut BTreeMap<usize, AstMatch>,
    state: usize,
    candidate: AstMatch,
) -> bool {
    match states.get(&state) {
        Some(previous) if !ast_is_better(&candidate, previous) => false,
        _ => {
            states.insert(state, candidate);
            true
        }
    }
}

fn ast_apply(
    pattern: &AstPattern,
    elements: &[SyntaxElement],
    states: Vec<AstMatch>,
    selected_label: u16,
    work: &mut usize,
) -> Vec<AstMatch> {
    match pattern {
        AstPattern::Atom { kind, label } => {
            *work += states.len();
            ast_dedup(
                states
                    .into_iter()
                    .filter_map(|mut state| {
                        let element = elements.get(state.pos)?;
                        let actual = element.kind();
                        if actual != *kind && actual != SyntaxKind::Missing {
                            return None;
                        }
                        state.pos += 1;
                        state.score += usize::from(actual == *kind);
                        if *label == Some(selected_label) {
                            state.field_count += 1;
                            state.fields = Some(Rc::new(AstCapture {
                                previous: state.fields,
                                element: (actual != SyntaxKind::Missing)
                                    .then(|| element.clone()),
                            }));
                        }
                        Some(state)
                    })
                    .collect(),
            )
        }
        AstPattern::Seq(patterns) => patterns.iter().fold(states, |states, pattern| {
            ast_apply(pattern, elements, states, selected_label, work)
        }),
        AstPattern::Alt(patterns) => ast_dedup(
            patterns
                .iter()
                .flat_map(|pattern| {
                    ast_apply(
                        pattern,
                        elements,
                        ast_clone_states(&states, work),
                        selected_label,
                        work,
                    )
                })
                .collect(),
        ),
        AstPattern::Opt(pattern) => {
            let mut matches = ast_clone_states(&states, work);
            matches.extend(ast_apply(pattern, elements, states, selected_label, work));
            ast_dedup(matches)
        }
        AstPattern::Rep(pattern) => {
            let mut matches = ast_dedup(states)
                .into_iter()
                .map(|state| (state.pos, state))
                .collect::<BTreeMap<_, _>>();
            *work += matches.len();
            let mut pending = matches.keys().copied().collect::<BTreeSet<_>>();
            while let Some(position) = pending.pop_first() {
                let frontier = vec![matches
                    .get(&position)
                    .expect("pending repetition endpoint must have a match")
                    .clone()];
                let next = ast_apply(pattern, elements, frontier, selected_label, work);
                for state in ast_dedup(next) {
                    if state.pos <= position {
                        continue;
                    }
                    match matches.get(&state.pos) {
                        None => {
                            *work += 1;
                            pending.insert(state.pos);
                            matches.insert(state.pos, state);
                        }
                        Some(previous) if ast_is_better(&state, previous) => {
                            debug_assert!(
                                pending.contains(&state.pos),
                                "a forward repetition endpoint must improve before expansion"
                            );
                            matches.insert(state.pos, state);
                        }
                        Some(_) => {}
                    }
                }
            }
            matches.into_values().collect()
        }
    }
}

fn ast_clone_states(states: &[AstMatch], work: &mut usize) -> Vec<AstMatch> {
    *work += states.len();
    states.to_vec()
}

fn ast_is_better(candidate: &AstMatch, previous: &AstMatch) -> bool {
    (candidate.score, candidate.field_count) > (previous.score, previous.field_count)
}

fn ast_dedup(states: Vec<AstMatch>) -> Vec<AstMatch> {
    let mut best = BTreeMap::<usize, AstMatch>::new();
    for state in states {
        match best.get(&state.pos) {
            Some(previous) if !ast_is_better(&state, previous) => {}
            _ => {
                best.insert(state.pos, state);
            }
        }
    }
    best.into_values().collect()
}

#[cfg(test)]
mod ast_matcher_tests {
    use super::*;

    const REPEATED_VALUE: AstPattern = AstPattern::Atom {
        kind: SyntaxKind::Ident,
        label: Some(0),
    };
    const REPEATED_VALUES: AstPattern = AstPattern::Rep(&REPEATED_VALUE);
    const TRAILING_VALUE: AstPattern = AstPattern::Atom {
        kind: SyntaxKind::Eof,
        label: Some(1),
    };
    const REPEATED_THEN_TRAILING_PARTS: [AstPattern; 2] = [REPEATED_VALUES, TRAILING_VALUE];
    const REPEATED_THEN_TRAILING: AstPattern =
        AstPattern::Seq(&REPEATED_THEN_TRAILING_PARTS);

    const LEFT_VALUE: AstPattern = AstPattern::Atom {
        kind: SyntaxKind::Ident,
        label: Some(0),
    };
    const RIGHT_VALUE: AstPattern = AstPattern::Atom {
        kind: SyntaxKind::Ident,
        label: Some(1),
    };
    const OVERLAPPING_BRANCHES: [AstPattern; 2] = [LEFT_VALUE, RIGHT_VALUE];
    const OVERLAPPING_LABELS: AstPattern = AstPattern::Alt(&OVERLAPPING_BRANCHES);

    const RECOVERED_LONG_PREFIX: AstPattern = AstPattern::Atom {
        kind: SyntaxKind::Ident,
        label: None,
    };
    const RECOVERED_COMMA: AstPattern = AstPattern::Atom {
        kind: SyntaxKind::Comma,
        label: Some(0),
    };
    const RECOVERED_LONG_PARTS: [AstPattern; 2] = [RECOVERED_LONG_PREFIX, RECOVERED_COMMA];
    const RECOVERED_LONG: AstPattern = AstPattern::Seq(&RECOVERED_LONG_PARTS);
    const RECOVERED_BRANCHES: [AstPattern; 2] = [RECOVERED_LONG, RECOVERED_COMMA];
    const RECOVERED_ALTERNATIVE: AstPattern = AstPattern::Alt(&RECOVERED_BRANCHES);
    const RECOVERED_REPETITION: AstPattern = AstPattern::Rep(&RECOVERED_ALTERNATIVE);

    const NESTED_VALUE: AstPattern = AstPattern::Atom {
        kind: SyntaxKind::Ident,
        label: None,
    };
    const NESTED_VALUES: AstPattern = AstPattern::Rep(&NESTED_VALUE);
    const NESTED_END: AstPattern = AstPattern::Atom {
        kind: SyntaxKind::Comma,
        label: Some(0),
    };
    const NESTED_ITERATION_PARTS: [AstPattern; 2] = [NESTED_VALUES, NESTED_END];
    const NESTED_ITERATION: AstPattern = AstPattern::Seq(&NESTED_ITERATION_PARTS);
    const NESTED_REPETITION: AstPattern = AstPattern::Rep(&NESTED_ITERATION);

    fn synthetic_node(values: usize, eof: bool) -> SyntaxNode {
        let mut builder = rowan::GreenNodeBuilder::new();
        builder.start_node(rowan::SyntaxKind(SyntaxKind::Source as u16));
        for _ in 0..values {
            builder.token(rowan::SyntaxKind(SyntaxKind::Ident as u16), "value");
        }
        if eof {
            builder.token(rowan::SyntaxKind(SyntaxKind::Eof as u16), "");
        }
        builder.finish_node();
        SyntaxNode::new_root(builder.finish())
    }

    fn synthetic_kinds(kinds: &[SyntaxKind]) -> SyntaxNode {
        let mut builder = rowan::GreenNodeBuilder::new();
        builder.start_node(rowan::SyntaxKind(SyntaxKind::Source as u16));
        for kind in kinds {
            match kind {
                SyntaxKind::Missing => {
                    builder.start_node(rowan::SyntaxKind(SyntaxKind::Missing as u16));
                    builder.finish_node();
                }
                SyntaxKind::Ident => {
                    builder.token(rowan::SyntaxKind(SyntaxKind::Ident as u16), "value");
                }
                SyntaxKind::Comma => {
                    builder.token(rowan::SyntaxKind(SyntaxKind::Comma as u16), ",");
                }
                _ => panic!("unsupported synthetic kind: {kind:?}"),
            }
        }
        builder.finish_node();
        SyntaxNode::new_root(builder.finish())
    }

    #[test]
    fn repetition_uses_linear_frontier_work_and_persistent_captures() {
        let mut previous_work = None;
        for count in [100, 200, 400, 800, 1_600] {
            let node = synthetic_node(count, true);
            let (repeated, repeated_work) =
                ast_fields_with_work(&node, &REPEATED_THEN_TRAILING, 0);
            let (trailing, trailing_work) =
                ast_fields_with_work(&node, &REPEATED_THEN_TRAILING, 1);

            assert_eq!(repeated.len(), count);
            assert!(repeated.iter().all(Option::is_some));
            assert_eq!(trailing.len(), 1);
            assert!(trailing[0].is_some());
            assert_eq!(repeated_work, 3 * count + 3);
            assert_eq!(trailing_work, 3 * count + 3);
            if let Some(previous) = previous_work {
                assert!(repeated_work <= 2 * previous + 8);
            }
            previous_work = Some(repeated_work);
        }
    }

    #[test]
    fn overlapping_alternatives_prefer_the_selected_label_capture() {
        let node = synthetic_node(1, false);
        let left = ast_fields(&node, &OVERLAPPING_LABELS, 0);
        let right = ast_fields(&node, &OVERLAPPING_LABELS, 1);

        assert_eq!(left.len(), 1);
        assert_eq!(left[0].as_ref().unwrap().kind(), SyntaxKind::Ident);
        assert_eq!(right.len(), 1);
        assert_eq!(right[0].as_ref().unwrap().kind(), SyntaxKind::Ident);
    }

    #[test]
    fn missing_prefix_improves_an_endpoint_before_it_is_expanded() {
        let recovered = synthetic_kinds(&[
            SyntaxKind::Missing,
            SyntaxKind::Comma,
            SyntaxKind::Comma,
        ]);
        let fields = ast_fields(&recovered, &RECOVERED_REPETITION, 0);
        assert_eq!(fields.len(), 3);
        assert!(fields[0].is_none());
        assert_eq!(fields.into_iter().flatten().count(), 2);

        let long_then_short = synthetic_kinds(&[
            SyntaxKind::Ident,
            SyntaxKind::Comma,
            SyntaxKind::Comma,
        ]);
        let fields = ast_fields(&long_then_short, &RECOVERED_REPETITION, 0);
        assert_eq!(fields.len(), 2);
        assert!(fields.iter().all(Option::is_some));

        let three_short = synthetic_kinds(&[
            SyntaxKind::Comma,
            SyntaxKind::Comma,
            SyntaxKind::Comma,
        ]);
        let fields = ast_fields(&three_short, &RECOVERED_REPETITION, 0);
        assert_eq!(fields.len(), 3);
        assert!(fields.iter().all(Option::is_some));
    }

    #[test]
    fn nested_repetition_uses_bounded_automaton_work() {
        let mut previous_work = None;
        for count in [50, 100, 200, 400] {
            let node = synthetic_kinds(&vec![SyntaxKind::Missing; count]);
            let (fields, work) = ast_fields_with_work(&node, &NESTED_REPETITION, 0);

            assert_eq!(fields.len(), count);
            assert!(fields.iter().all(Option::is_none));
            assert_eq!(work, 11 * count + 6);
            if let Some(previous) = previous_work {
                assert!(work <= 2 * previous + 6);
            }
            previous_work = Some(work);
        }
    }
}

"#;
const REQUIRED_LEXICAL_KINDS: [&str; 8] = [
    "trivia:WHITESPACE",
    "trivia:NEWLINE",
    "trivia:LINE_COMMENT",
    "trivia:BLOCK_COMMENT",
    "special:TOMBSTONE",
    "token:@",
    "special:ERROR_TOKEN",
    "special:MISSING",
];

pub struct Inputs<'a> {
    pub grammar: &'a str,
    pub production_map: &'a str,
    pub kind_ids: &'a str,
    pub lexical_kinds: &'a str,
    pub language_spec: &'a str,
}

#[derive(Debug)]
pub struct Generated {
    pub kinds: String,
    pub ast: String,
    pub inventory: String,
}

impl Generated {
    pub fn files(&self) -> [(&str, &[u8]); 3] {
        [
            ("kinds.rs", self.kinds.as_bytes()),
            ("ast.rs", self.ast.as_bytes()),
            ("inventory.rs", self.inventory.as_bytes()),
        ]
    }
}

pub fn render(inputs: &Inputs<'_>) -> Result<Generated, String> {
    let grammar = inputs
        .grammar
        .parse::<Grammar>()
        .map_err(|error| format!("invalid ungrammar: {error}"))?;
    let documented = documented_productions(inputs.language_spec)?;
    let mapping = parse_mapping(inputs.production_map)?;
    validate_mapping(&grammar, &documented, &mapping)?;
    let ids = parse_kind_ids(inputs.kind_ids)?;
    let lexical = parse_lexical_kinds(inputs.lexical_kinds)?;
    validate_kind_ids(&grammar, &lexical, &ids)?;
    let typed_ast = typed_ast_model(&grammar)?;

    Ok(Generated {
        kinds: render_kinds(&grammar, &lexical, &ids),
        ast: render_ast(&grammar, &typed_ast),
        inventory: render_inventory(&grammar, &mapping, &lexical, &typed_ast),
    })
}

fn parse_lexical_kinds(text: &str) -> Result<BTreeSet<String>, String> {
    let kinds = text
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .map(ToOwned::to_owned)
        .collect::<BTreeSet<_>>();
    let expected = REQUIRED_LEXICAL_KINDS.map(ToOwned::to_owned).into();
    if kinds != expected {
        return Err(
            "lexical kind inventory must contain every required trivia and tombstone kind".into(),
        );
    }
    Ok(kinds)
}

fn documented_productions(specification: &str) -> Result<BTreeSet<String>, String> {
    let start = specification
        .find(GRAMMAR_FENCE_HEADER)
        .ok_or("language specification has no section 3.4 grammar fence")?;
    let grammar = &specification[start + GRAMMAR_FENCE_HEADER.len()..];
    let grammar = grammar
        .split_once("\n```")
        .ok_or("language specification grammar fence is not closed")?
        .0;
    let names = grammar
        .lines()
        .filter_map(|line| line.split_once('=').map(|(left, _)| left.trim()))
        .filter(|name| {
            !name.is_empty()
                && name
                    .bytes()
                    .all(|byte| byte.is_ascii_lowercase() || byte == b'-')
        })
        .map(ToOwned::to_owned)
        .collect::<BTreeSet<_>>();
    if names.is_empty() {
        return Err("language specification grammar fence has no productions".into());
    }
    Ok(names)
}

fn parse_mapping(text: &str) -> Result<BTreeMap<String, String>, String> {
    let mut result = BTreeMap::new();
    for (line_number, line) in text.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let (production, node) = split_tsv(line)
            .ok_or_else(|| format!("production map line {} must contain a tab", line_number + 1))?;
        if production.is_empty()
            || node.is_empty()
            || result.insert(production.into(), node.into()).is_some()
        {
            return Err(format!(
                "invalid or duplicate production map line {}",
                line_number + 1
            ));
        }
    }
    Ok(result)
}

fn validate_mapping(
    grammar: &Grammar,
    documented: &BTreeSet<String>,
    mapping: &BTreeMap<String, String>,
) -> Result<(), String> {
    let mapped = mapping.keys().cloned().collect::<BTreeSet<_>>();
    if &mapped != documented {
        let missing = documented.difference(&mapped).cloned().collect::<Vec<_>>();
        let orphan = mapped.difference(documented).cloned().collect::<Vec<_>>();
        return Err(format!(
            "production map mismatch; missing={missing:?}, orphan={orphan:?}"
        ));
    }
    let nodes = grammar
        .iter()
        .map(|node| grammar[node].name.clone())
        .collect::<BTreeSet<_>>();
    let mapped_nodes = mapping.values().cloned().collect::<BTreeSet<_>>();
    if nodes != mapped_nodes {
        let missing = nodes.difference(&mapped_nodes).cloned().collect::<Vec<_>>();
        let orphan = mapped_nodes.difference(&nodes).cloned().collect::<Vec<_>>();
        return Err(format!(
            "grammar node mapping mismatch; missing={missing:?}, orphan={orphan:?}"
        ));
    }
    Ok(())
}

fn parse_kind_ids(text: &str) -> Result<BTreeMap<String, u16>, String> {
    let mut result = BTreeMap::new();
    let mut used = BTreeSet::new();
    for (line_number, line) in text.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let (name, raw_id) = split_tsv(line)
            .ok_or_else(|| format!("kind ID line {} must contain a tab", line_number + 1))?;
        let id = raw_id
            .parse::<u16>()
            .map_err(|_| format!("kind ID line {} has an invalid ID", line_number + 1))?;
        if name.is_empty() || result.insert(name.into(), id).is_some() || !used.insert(id) {
            return Err(format!(
                "duplicate kind name or ID on line {}",
                line_number + 1
            ));
        }
    }
    Ok(result)
}

fn split_tsv(line: &str) -> Option<(&str, &str)> {
    line.split_once('\t')
}

fn validate_kind_ids(
    grammar: &Grammar,
    lexical: &BTreeSet<String>,
    ids: &BTreeMap<String, u16>,
) -> Result<(), String> {
    let mut expected = BTreeSet::from(["special:ERROR".to_owned()]);
    expected.extend(
        grammar
            .tokens()
            .map(|token| format!("token:{}", grammar[token].name)),
    );
    expected.extend(
        grammar
            .iter()
            .map(|node| format!("node:{}", grammar[node].name)),
    );
    expected.extend(lexical.iter().cloned());
    let actual = ids.keys().cloned().collect::<BTreeSet<_>>();
    if expected != actual {
        let missing = expected.difference(&actual).cloned().collect::<Vec<_>>();
        let orphan = actual.difference(&expected).cloned().collect::<Vec<_>>();
        return Err(format!(
            "stable kind ID mismatch; missing={missing:?}, orphan={orphan:?}"
        ));
    }
    if ids.get("special:ERROR") != Some(&0) {
        return Err("special:ERROR must retain stable ID 0".into());
    }
    let mut variants = BTreeSet::new();
    for key in ids {
        if !variants.insert(kind_variant(key.0)) {
            return Err(format!(
                "kind names produce a duplicate Rust variant: {}",
                key.0
            ));
        }
    }
    Ok(())
}

fn render_kinds(
    grammar: &Grammar,
    lexical: &BTreeSet<String>,
    ids: &BTreeMap<String, u16>,
) -> String {
    let mut entries = ids
        .iter()
        .map(|(name, id)| (*id, name.as_str()))
        .collect::<Vec<_>>();
    entries.sort_unstable();
    let mut output = String::from(MARKER);
    output.push_str("#[repr(u16)]\n#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]\npub enum SyntaxKind {\n");
    for (id, name) in &entries {
        output.push_str(&format!("    {} = {id},\n", kind_variant(name)));
    }
    output.push_str("}\n\nimpl SyntaxKind {\n    #[must_use]\n    pub const fn from_raw(raw: u16) -> Option<Self> {\n        match raw {\n");
    for (id, name) in &entries {
        output.push_str(&format!(
            "            {id} => Some(Self::{}),\n",
            kind_variant(name)
        ));
    }
    output.push_str("            _ => None,\n        }\n    }\n\n    #[must_use]\n    pub const fn is_token(self) -> bool {\n        matches!(self,\n");
    let token_variants = grammar
        .tokens()
        .map(|token| kind_variant(&format!("token:{}", grammar[token].name)))
        .chain(
            lexical
                .iter()
                .filter(|kind| {
                    kind.starts_with("trivia:")
                        || *kind == "token:@"
                        || *kind == "special:ERROR_TOKEN"
                })
                .map(|kind| kind_variant(kind)),
        )
        .collect::<Vec<_>>();
    output.push_str(&format!(
        "            {}\n",
        token_variants
            .iter()
            .map(|variant| format!("Self::{variant}"))
            .collect::<Vec<_>>()
            .join(" | ")
    ));
    output.push_str("        )\n    }\n}\n");
    output
}

fn render_ast(grammar: &Grammar, typed_ast: &[TypedNode]) -> String {
    let mut output = String::from(MARKER);
    output.push_str(AST_PRELUDE);
    for typed_node in typed_ast.iter().filter(|node| !node.labels.is_empty()) {
        output.push_str(&format!(
            "const AST_PATTERN_{}: AstPattern = {};\n\n",
            snake(&grammar[typed_node.node].name).to_ascii_uppercase(),
            render_pattern(
                &grammar[typed_node.node].rule,
                grammar,
                &typed_node.labels,
                None
            ),
        ));
    }
    for typed_node in typed_ast {
        let name = &grammar[typed_node.node].name;
        output.push_str(&format!("#[derive(Clone, Debug, Eq, Hash, PartialEq)]\npub struct {name} {{ syntax: SyntaxNode }}\n\n"));
        output.push_str(&format!("impl AstNode for {name} {{\n    type Language = AllenLanguage;\n\n    fn can_cast(kind: SyntaxKind) -> bool {{ kind == SyntaxKind::{} }}\n\n    fn cast(syntax: SyntaxNode) -> Option<Self> {{ Self::can_cast(syntax.kind()).then_some(Self {{ syntax }}) }}\n\n    fn syntax(&self) -> &SyntaxNode {{ &self.syntax }}\n}}\n\n", kind_variant(&format!("node:{name}"))));
        output.push_str(&format!("impl {name} {{\n    #[must_use]\n    pub fn children(&self) -> impl Iterator<Item = SyntaxNode> + '_ {{ self.syntax.children() }}\n\n    /// Returns recovery nodes and tokens owned directly by this grammar node.\n    #[must_use]\n    pub fn errors(&self) -> impl Iterator<Item = AstError> + '_ {{\n        self.syntax.children_with_tokens().filter_map(AstError::cast)\n    }}\n"));
        for accessor in &typed_node.accessors {
            render_accessor(&mut output, grammar, typed_node, accessor);
        }
        output.push_str("}\n\n");
    }
    if output.ends_with("\n\n") {
        output.pop();
    }
    output
}

fn render_inventory(
    grammar: &Grammar,
    mapping: &BTreeMap<String, String>,
    lexical: &BTreeSet<String>,
    typed_ast: &[TypedNode],
) -> String {
    let mut output = String::from(MARKER);
    output.push_str("/// Normative section 3.4 production to concrete-node mapping.\npub const PRODUCTION_INVENTORY: &[(&str, &str)] = &[\n");
    for (production, node) in mapping {
        output.push_str(&format!("    ({production:?}, {node:?}),\n"));
    }
    output.push_str("];\n\n/// Lexical terminals, represented as tokens rather than AST nodes.\npub const TOKEN_INVENTORY: &[&str] = &[\n");
    for token in grammar.tokens() {
        output.push_str(&format!("    {:?},\n", grammar[token].name));
    }
    output.push_str(
        "];\n\n/// Non-grammar lexical and recovery kinds.\npub const LEXICAL_KIND_INVENTORY: &[&str] = &[\n",
    );
    for kind in lexical {
        output.push_str(&format!("    {kind:?},\n"));
    }
    output.push_str(
        "];\n\n/// Concrete grammar node names.\npub const NODE_INVENTORY: &[&str] = &[\n",
    );
    for node in grammar.iter() {
        output.push_str(&format!("    {:?},\n", grammar[node].name));
    }
    output.push_str("];\n\n/// Grammar nodes with one generated public typed wrapper each.\npub const TYPED_AST_WRAPPER_INVENTORY: &[&str] = &[\n");
    for typed_node in typed_ast {
        output.push_str(&format!("    {:?},\n", grammar[typed_node.node].name));
    }
    output.push_str("];\n\n/// Exact direct-child/token accessor coverage: wrapper, method, target, cardinality, label.\n///\n/// Required and optional singular relationships both return `Option`; `many`\n/// relationships return typed iterators. An empty label denotes a homogeneous\n/// target-derived accessor. Every wrapper also exposes `errors`.\npub const TYPED_AST_ACCESSOR_INVENTORY: &[(&str, &str, &str, &str, &str)] = &[\n");
    for typed_node in typed_ast {
        let wrapper = &grammar[typed_node.node].name;
        for accessor in &typed_node.accessors {
            output.push_str(&format!(
                "    ({wrapper:?}, {:?}, {:?}, {:?}, {:?}),\n",
                accessor.method,
                accessor.target.inventory_name(grammar),
                accessor.cardinality.inventory_name(),
                accessor.label.as_deref().unwrap_or(""),
            ));
        }
    }
    output.push_str("];\n");
    output
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum AccessorTarget {
    Node(Node),
    Token(Token),
}

impl AccessorTarget {
    fn inventory_name(self, grammar: &Grammar) -> String {
        match self {
            Self::Node(node) => format!("node:{}", grammar[node].name),
            Self::Token(token) => format!("token:{}", grammar[token].name),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum Cardinality {
    Required,
    Optional,
    Many,
}

impl Cardinality {
    const fn inventory_name(self) -> &'static str {
        match self {
            Self::Required => "required",
            Self::Optional => "optional",
            Self::Many => "many",
        }
    }
}

#[derive(Debug)]
struct Accessor {
    target: AccessorTarget,
    cardinality: Cardinality,
    method: String,
    label: Option<String>,
    selector: AccessorSelector,
}

#[derive(Debug)]
struct TypedNode {
    node: Node,
    accessors: Vec<Accessor>,
    labels: Vec<String>,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum AccessorSelector {
    Aggregate,
    Label(u16),
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct FieldKey {
    target: AccessorTarget,
    label: Option<String>,
}

#[derive(Clone, Debug)]
enum PatternEdge {
    Epsilon(usize),
    Symbol(String, usize),
}

#[derive(Debug)]
struct PatternNfa {
    edges: Vec<Vec<PatternEdge>>,
    start: usize,
    accept: usize,
}

impl PatternNfa {
    fn from_rule(rule: &Rule, grammar: &Grammar) -> Self {
        let mut nfa = Self {
            edges: Vec::new(),
            start: 0,
            accept: 0,
        };
        let (start, accept) = nfa.fragment(rule, grammar);
        nfa.start = start;
        nfa.accept = accept;
        nfa
    }

    fn state(&mut self) -> usize {
        let state = self.edges.len();
        self.edges.push(Vec::new());
        state
    }

    fn epsilon(&mut self, from: usize, to: usize) {
        self.edges[from].push(PatternEdge::Epsilon(to));
    }

    fn fragment(&mut self, rule: &Rule, grammar: &Grammar) -> (usize, usize) {
        match rule {
            Rule::Node(node) => self.symbol(format!("node:{}", grammar[*node].name)),
            Rule::Token(token) => self.symbol(format!("token:{}", grammar[*token].name)),
            Rule::Labeled { rule, .. } => self.fragment(rule, grammar),
            Rule::Opt(rule) => {
                let start = self.state();
                let accept = self.state();
                let (inner_start, inner_accept) = self.fragment(rule, grammar);
                self.epsilon(start, accept);
                self.epsilon(start, inner_start);
                self.epsilon(inner_accept, accept);
                (start, accept)
            }
            Rule::Rep(rule) => {
                let start = self.state();
                let accept = self.state();
                let (inner_start, inner_accept) = self.fragment(rule, grammar);
                self.epsilon(start, accept);
                self.epsilon(start, inner_start);
                self.epsilon(inner_accept, inner_start);
                self.epsilon(inner_accept, accept);
                (start, accept)
            }
            Rule::Seq(rules) => {
                let start = self.state();
                let mut tail = start;
                for rule in rules {
                    let (next_start, next_accept) = self.fragment(rule, grammar);
                    self.epsilon(tail, next_start);
                    tail = next_accept;
                }
                (start, tail)
            }
            Rule::Alt(rules) => {
                let start = self.state();
                let accept = self.state();
                for rule in rules {
                    let (branch_start, branch_accept) = self.fragment(rule, grammar);
                    self.epsilon(start, branch_start);
                    self.epsilon(branch_accept, accept);
                }
                (start, accept)
            }
        }
    }

    fn symbol(&mut self, symbol: String) -> (usize, usize) {
        let start = self.state();
        let accept = self.state();
        self.edges[start].push(PatternEdge::Symbol(symbol, accept));
        (start, accept)
    }

    fn start_closure(&self) -> Vec<usize> {
        self.epsilon_closure([self.start])
    }

    fn epsilon_closure(&self, seeds: impl IntoIterator<Item = usize>) -> Vec<usize> {
        let mut closure = seeds.into_iter().collect::<BTreeSet<_>>();
        let mut pending = closure.iter().copied().collect::<Vec<_>>();
        while let Some(state) = pending.pop() {
            for edge in &self.edges[state] {
                if let PatternEdge::Epsilon(next) = edge {
                    if closure.insert(*next) {
                        pending.push(*next);
                    }
                }
            }
        }
        closure.into_iter().collect()
    }

    fn symbols(&self, states: &[usize]) -> BTreeSet<&str> {
        states
            .iter()
            .flat_map(|state| &self.edges[*state])
            .filter_map(|edge| match edge {
                PatternEdge::Symbol(symbol, _) => Some(symbol.as_str()),
                PatternEdge::Epsilon(_) => None,
            })
            .collect()
    }

    fn advance(&self, states: &[usize], symbol: &str) -> Vec<usize> {
        self.epsilon_closure(states.iter().flat_map(|state| {
            self.edges[*state].iter().filter_map(|edge| match edge {
                PatternEdge::Symbol(candidate, next) if candidate == symbol => Some(*next),
                PatternEdge::Epsilon(_) | PatternEdge::Symbol(_, _) => None,
            })
        }))
    }

    fn accepts(&self, states: &[usize]) -> bool {
        states.binary_search(&self.accept).is_ok()
    }
}

#[derive(Clone, Debug, Eq, Ord, PartialEq, PartialOrd)]
struct DecoderPair {
    left: Vec<usize>,
    right: Vec<usize>,
    boundaries_differ: bool,
}

fn validate_observable_repetitions(
    rule: &Rule,
    grammar: &Grammar,
    owner: &str,
) -> Result<(), String> {
    match rule {
        Rule::Rep(repeated) => {
            if repetition_boundaries_are_ambiguous(repeated, grammar) {
                return Err(format!(
                    "typed AST repetition ambiguity on {owner}: repeated child/token pattern permits different iteration boundaries"
                ));
            }
            validate_observable_repetitions(repeated, grammar, owner)
        }
        Rule::Labeled { rule, .. } | Rule::Opt(rule) => {
            validate_observable_repetitions(rule, grammar, owner)
        }
        Rule::Seq(rules) | Rule::Alt(rules) => {
            for rule in rules {
                validate_observable_repetitions(rule, grammar, owner)?;
            }
            Ok(())
        }
        Rule::Node(_) | Rule::Token(_) => Ok(()),
    }
}

/// Returns true when the repeated body's direct-kind language has two distinct
/// iteration-boundary factorizations. The finite decoder-product search handles
/// alternatives, optionals, and nested repetitions without enumerating strings.
fn repetition_boundaries_are_ambiguous(rule: &Rule, grammar: &Grammar) -> bool {
    let nfa = PatternNfa::from_rule(rule, grammar);
    let start = nfa.start_closure();
    if nfa.accepts(&start) {
        return true;
    }

    let initial = DecoderPair {
        left: start.clone(),
        right: start.clone(),
        boundaries_differ: false,
    };
    let mut seen = BTreeSet::from([initial.clone()]);
    let mut pending = VecDeque::from([initial]);
    while let Some(pair) = pending.pop_front() {
        let left_symbols = nfa.symbols(&pair.left);
        let right_symbols = nfa.symbols(&pair.right);
        for symbol in left_symbols.intersection(&right_symbols) {
            let left = nfa.advance(&pair.left, symbol);
            let right = nfa.advance(&pair.right, symbol);
            let left_accepts = nfa.accepts(&left);
            let right_accepts = nfa.accepts(&right);
            // Both decoders have consumed the same direct-kind sequence. If
            // their earlier cuts differ and both can end here, the sequence has
            // two repetition factorizations and a seen endpoint would need
            // re-expansion to preserve every possible capture.
            if pair.boundaries_differ && left_accepts && right_accepts {
                return true;
            }

            let left_cuts = [false, true].into_iter().filter(|cut| !cut || left_accepts);
            let right_cuts = [false, true]
                .into_iter()
                .filter(|cut| !cut || right_accepts)
                .collect::<Vec<_>>();
            for left_cut in left_cuts {
                for &right_cut in &right_cuts {
                    let next = DecoderPair {
                        left: if left_cut {
                            start.clone()
                        } else {
                            left.clone()
                        },
                        right: if right_cut {
                            start.clone()
                        } else {
                            right.clone()
                        },
                        boundaries_differ: pair.boundaries_differ || left_cut != right_cut,
                    };
                    if seen.insert(next.clone()) {
                        pending.push_back(next);
                    }
                }
            }
        }
    }
    false
}

fn typed_ast_model(grammar: &Grammar) -> Result<Vec<TypedNode>, String> {
    grammar
        .iter()
        .map(|node| {
            let mut fields = Vec::new();
            collect_fields(&grammar[node].rule, None, &mut fields)?;
            let labels = fields
                .iter()
                .filter_map(|field| field.label.clone())
                .collect::<Vec<_>>();
            if !labels.is_empty() {
                validate_observable_repetitions(&grammar[node].rule, grammar, &grammar[node].name)?;
            }
            let mut used_methods = BTreeSet::from([
                "children".to_owned(),
                "errors".to_owned(),
                "syntax".to_owned(),
            ]);
            let accessors = fields
                .into_iter()
                .map(|field| {
                    let count = field_count(
                        &grammar[node].rule,
                        field.target,
                        field.label.as_deref(),
                        None,
                    );
                    let cardinality = count.cardinality();
                    let method =
                        accessor_method(grammar, field.target, cardinality, field.label.as_deref());
                    if !used_methods.insert(method.clone()) {
                        return Err(format!(
                            "typed AST accessor collision on {}.{method} for {}",
                            grammar[node].name,
                            field.target.inventory_name(grammar),
                        ));
                    }
                    let selector = field
                        .label
                        .as_ref()
                        .map(|label| {
                            labels
                                .iter()
                                .position(|candidate| candidate == label)
                                .and_then(|index| u16::try_from(index).ok())
                                .map(AccessorSelector::Label)
                                .ok_or_else(|| {
                                    format!("too many typed AST labels on {}", grammar[node].name)
                                })
                        })
                        .transpose()?
                        .unwrap_or(AccessorSelector::Aggregate);
                    Ok(Accessor {
                        target: field.target,
                        cardinality,
                        method,
                        label: field.label,
                        selector,
                    })
                })
                .collect::<Result<Vec<_>, String>>()?;
            Ok(TypedNode {
                node,
                accessors,
                labels,
            })
        })
        .collect()
}

fn collect_fields(
    rule: &Rule,
    active_label: Option<&str>,
    fields: &mut Vec<FieldKey>,
) -> Result<(), String> {
    match rule {
        Rule::Node(node) => push_unique_field(
            fields,
            FieldKey {
                target: AccessorTarget::Node(*node),
                label: active_label.map(ToOwned::to_owned),
            },
        )?,
        Rule::Token(token) => push_unique_field(
            fields,
            FieldKey {
                target: AccessorTarget::Token(*token),
                label: active_label.map(ToOwned::to_owned),
            },
        )?,
        Rule::Labeled { label, rule } => {
            if active_label.is_some() {
                return Err(format!("nested typed AST label `{label}` is unsupported"));
            }
            collect_fields(rule, Some(label), fields)?;
        }
        Rule::Opt(rule) | Rule::Rep(rule) => {
            collect_fields(rule, active_label, fields)?;
        }
        Rule::Seq(rules) | Rule::Alt(rules) => {
            for rule in rules {
                collect_fields(rule, active_label, fields)?;
            }
        }
    }
    Ok(())
}

fn push_unique_field(fields: &mut Vec<FieldKey>, field: FieldKey) -> Result<(), String> {
    if let Some(label) = &field.label {
        if let Some(previous) = fields
            .iter()
            .find(|candidate| candidate.label.as_ref() == Some(label))
        {
            if previous.target != field.target {
                return Err(format!(
                    "typed AST label `{label}` refers to more than one target"
                ));
            }
            return Ok(());
        }
    }
    if !fields.contains(&field) {
        fields.push(field);
    }
    Ok(())
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct Count {
    min: u8,
    max: u8,
}

impl Count {
    const ZERO: Self = Self { min: 0, max: 0 };
    const ONE: Self = Self { min: 1, max: 1 };

    fn cardinality(self) -> Cardinality {
        match (self.min, self.max) {
            (1, 1) => Cardinality::Required,
            (0, 1) => Cardinality::Optional,
            _ => Cardinality::Many,
        }
    }

    fn sequence(self, other: Self) -> Self {
        Self {
            min: self.min.saturating_add(other.min).min(2),
            max: self.max.saturating_add(other.max).min(2),
        }
    }

    fn alternative(self, other: Self) -> Self {
        Self {
            min: self.min.min(other.min),
            max: self.max.max(other.max),
        }
    }
}

fn field_count(
    rule: &Rule,
    target: AccessorTarget,
    label: Option<&str>,
    active_label: Option<&str>,
) -> Count {
    match rule {
        Rule::Node(node) => {
            Count::from(AccessorTarget::Node(*node) == target && active_label == label)
        }
        Rule::Token(token) => {
            Count::from(AccessorTarget::Token(*token) == target && active_label == label)
        }
        Rule::Labeled {
            label: rule_label,
            rule,
        } => field_count(rule, target, label, Some(rule_label)),
        Rule::Opt(rule) => Count {
            min: 0,
            ..field_count(rule, target, label, active_label)
        },
        Rule::Rep(rule) => {
            let inner = field_count(rule, target, label, active_label);
            Count {
                min: 0,
                max: u8::from(inner.max != 0) * 2,
            }
        }
        Rule::Seq(rules) => rules.iter().fold(Count::ZERO, |count, rule| {
            count.sequence(field_count(rule, target, label, active_label))
        }),
        Rule::Alt(rules) => rules
            .iter()
            .map(|rule| field_count(rule, target, label, active_label))
            .reduce(Count::alternative)
            .unwrap_or(Count::ZERO),
    }
}

impl From<bool> for Count {
    fn from(present: bool) -> Self {
        if present { Self::ONE } else { Self::ZERO }
    }
}

fn accessor_method(
    grammar: &Grammar,
    target: AccessorTarget,
    cardinality: Cardinality,
    label: Option<&str>,
) -> String {
    if let Some(label) = label {
        return match target {
            AccessorTarget::Node(_) => label.to_owned(),
            AccessorTarget::Token(_) if cardinality == Cardinality::Many => {
                format!("{label}_tokens")
            }
            AccessorTarget::Token(_) => format!("{label}_token"),
        };
    }
    match target {
        AccessorTarget::Node(node) => {
            let singular = snake(&grammar[node].name);
            if cardinality == Cardinality::Many {
                plural_snake(&singular)
            } else if singular == "type" {
                "ty".to_owned()
            } else {
                singular
            }
        }
        AccessorTarget::Token(token) => {
            let variant = kind_variant(&format!("token:{}", grammar[token].name));
            let base = snake(&variant);
            let base = base.strip_prefix("kw_").unwrap_or(&base);
            if cardinality == Cardinality::Many {
                format!("{base}_tokens")
            } else {
                format!("{base}_token")
            }
        }
    }
}

fn render_pattern(
    rule: &Rule,
    grammar: &Grammar,
    labels: &[String],
    active_label: Option<&str>,
) -> String {
    match rule {
        Rule::Node(node) => render_pattern_atom(
            &kind_variant(&format!("node:{}", grammar[*node].name)),
            labels,
            active_label,
        ),
        Rule::Token(token) => render_pattern_atom(
            &kind_variant(&format!("token:{}", grammar[*token].name)),
            labels,
            active_label,
        ),
        Rule::Labeled { label, rule } => render_pattern(rule, grammar, labels, Some(label)),
        Rule::Opt(rule) => format!(
            "AstPattern::Opt(&{})",
            render_pattern(rule, grammar, labels, active_label)
        ),
        Rule::Rep(rule) => format!(
            "AstPattern::Rep(&{})",
            render_pattern(rule, grammar, labels, active_label)
        ),
        Rule::Seq(rules) => format!(
            "AstPattern::Seq(&[{}])",
            rules
                .iter()
                .map(|rule| render_pattern(rule, grammar, labels, active_label))
                .collect::<Vec<_>>()
                .join(", ")
        ),
        Rule::Alt(rules) => format!(
            "AstPattern::Alt(&[{}])",
            rules
                .iter()
                .map(|rule| render_pattern(rule, grammar, labels, active_label))
                .collect::<Vec<_>>()
                .join(", ")
        ),
    }
}

fn render_pattern_atom(kind: &str, labels: &[String], active_label: Option<&str>) -> String {
    let label = active_label
        .and_then(|label| labels.iter().position(|candidate| candidate == label))
        .map_or_else(|| "None".to_owned(), |index| format!("Some({index})"));
    format!("AstPattern::Atom {{ kind: SyntaxKind::{kind}, label: {label} }}")
}

fn render_accessor(output: &mut String, grammar: &Grammar, owner: &TypedNode, accessor: &Accessor) {
    let method = &accessor.method;
    if let AccessorSelector::Label(label) = accessor.selector {
        render_labeled_accessor(output, grammar, owner, accessor, label);
        return;
    }
    match (accessor.target, accessor.cardinality) {
        (AccessorTarget::Node(node), Cardinality::Many) => {
            let child = &grammar[node].name;
            output.push_str(&format!(
                "\n    #[must_use]\n    pub fn {method}(&self) -> AstChildren<{child}> {{\n        support::children(&self.syntax)\n    }}\n"
            ));
        }
        (AccessorTarget::Node(node), _) => {
            let child = &grammar[node].name;
            output.push_str(&format!(
                "\n    #[must_use]\n    pub fn {method}(&self) -> Option<{child}> {{\n        support::child(&self.syntax)\n    }}\n"
            ));
        }
        (AccessorTarget::Token(token), Cardinality::Many) => {
            let kind = kind_variant(&format!("token:{}", grammar[token].name));
            output.push_str(&format!(
                "\n    #[must_use]\n    pub fn {method}(&self) -> impl Iterator<Item = SyntaxToken> + '_ {{\n        self.syntax.children_with_tokens().filter_map(rowan::NodeOrToken::into_token).filter(|token| token.kind() == SyntaxKind::{kind})\n    }}\n"
            ));
        }
        (AccessorTarget::Token(token), _) => {
            let kind = kind_variant(&format!("token:{}", grammar[token].name));
            output.push_str(&format!(
                "\n    #[must_use]\n    pub fn {method}(&self) -> Option<SyntaxToken> {{\n        support::token(&self.syntax, SyntaxKind::{kind})\n    }}\n"
            ));
        }
    }
}

fn render_labeled_accessor(
    output: &mut String,
    grammar: &Grammar,
    owner: &TypedNode,
    accessor: &Accessor,
    label: u16,
) {
    let method = &accessor.method;
    let pattern = format!(
        "AST_PATTERN_{}",
        snake(&grammar[owner.node].name).to_ascii_uppercase()
    );
    match (accessor.target, accessor.cardinality) {
        (AccessorTarget::Node(node), Cardinality::Many) => {
            let child = &grammar[node].name;
            output.push_str(&format!(
                "\n    #[must_use]\n    pub fn {method}(&self) -> impl Iterator<Item = {child}> {{\n        ast_fields(&self.syntax, &{pattern}, {label}).into_iter().flatten().filter_map(rowan::NodeOrToken::into_node).filter_map({child}::cast)\n    }}\n"
            ));
        }
        (AccessorTarget::Node(node), _) => {
            let child = &grammar[node].name;
            output.push_str(&format!(
                "\n    #[must_use]\n    pub fn {method}(&self) -> Option<{child}> {{\n        ast_fields(&self.syntax, &{pattern}, {label}).into_iter().next().flatten().and_then(rowan::NodeOrToken::into_node).and_then({child}::cast)\n    }}\n"
            ));
        }
        (AccessorTarget::Token(_), Cardinality::Many) => {
            output.push_str(&format!(
                "\n    #[must_use]\n    pub fn {method}(&self) -> impl Iterator<Item = SyntaxToken> {{\n        ast_fields(&self.syntax, &{pattern}, {label}).into_iter().flatten().filter_map(rowan::NodeOrToken::into_token)\n    }}\n"
            ));
        }
        (AccessorTarget::Token(_), _) => {
            output.push_str(&format!(
                "\n    #[must_use]\n    pub fn {method}(&self) -> Option<SyntaxToken> {{\n        ast_fields(&self.syntax, &{pattern}, {label}).into_iter().next().flatten().and_then(rowan::NodeOrToken::into_token)\n    }}\n"
            ));
        }
    }
}

fn kind_variant(key: &str) -> String {
    if key == "special:ERROR" {
        return "Error".into();
    }
    if let Some(value) = key.strip_prefix("node:") {
        return value.into();
    }
    if let Some(value) = key.strip_prefix("trivia:") {
        return pascal(value);
    }
    if let Some(value) = key.strip_prefix("special:") {
        return pascal(value);
    }
    let value = key.strip_prefix("token:").unwrap_or(key);
    match value {
        "EOF" => "Eof".into(),
        "Map" => "KwMapType".into(),
        "Prompt" => "KwPromptType".into(),
        "identifier" => "Ident".into(),
        "effect-id" => "EffectId".into(),
        "int-literal" => "IntLiteral".into(),
        "float-literal" => "FloatLiteral".into(),
        "string-literal" => "StringLiteral".into(),
        "bytes-literal" => "BytesLiteral".into(),
        "template-text-scalar" => "TemplateTextScalar".into(),
        "template-escape" => "TemplateEscape".into(),
        "{" => "LBrace".into(),
        "}" => "RBrace".into(),
        "[" => "LBracket".into(),
        "]" => "RBracket".into(),
        "(" => "LParen".into(),
        ")" => "RParen".into(),
        "," => "Comma".into(),
        ":" => "Colon".into(),
        ";" => "Semi".into(),
        "<" => "Lt".into(),
        ">" => "Gt".into(),
        "=" => "Eq".into(),
        "+=" => "PlusEq".into(),
        "-=" => "MinusEq".into(),
        "*=" => "StarEq".into(),
        "/=" => "SlashEq".into(),
        "%=" => "PercentEq".into(),
        ".." => "DotDot".into(),
        "_" => "Underscore".into(),
        "||" => "PipePipe".into(),
        "&&" => "AmpAmp".into(),
        "==" => "EqEq".into(),
        "!=" => "NotEq".into(),
        "<=" => "LtEq".into(),
        ">=" => "GtEq".into(),
        "+" => "Plus".into(),
        "-" => "Minus".into(),
        "*" => "Star".into(),
        "/" => "Slash".into(),
        "%" => "Percent".into(),
        "!" => "Bang".into(),
        "." => "Dot".into(),
        "?" => "Question".into(),
        "`" => "Backtick".into(),
        "${" => "TemplateExprStart".into(),
        "=>" => "FatArrow".into(),
        "@" => "At".into(),
        _ => format!("Kw{}", pascal(value)),
    }
}

fn pascal(value: &str) -> String {
    let mut output = String::new();
    for part in value
        .split(|character: char| !character.is_ascii_alphanumeric())
        .filter(|part| !part.is_empty())
    {
        let mut characters = part.chars();
        output.push(characters.next().unwrap_or_default().to_ascii_uppercase());
        output.push_str(&characters.as_str().to_ascii_lowercase());
    }
    output
}

fn snake(name: &str) -> String {
    let mut output = String::new();
    for (index, character) in name.char_indices() {
        if character.is_ascii_uppercase() && index != 0 {
            output.push('_');
        }
        output.push(character.to_ascii_lowercase());
    }
    output
}

fn plural_snake(name: &str) -> String {
    if let Some(stem) = name.strip_suffix('y') {
        return format!("{stem}ies");
    }
    if name.ends_with('s') {
        return format!("{name}_items");
    }
    format!("{name}s")
}

#[cfg(test)]
mod tests {
    use super::*;

    const SPEC: &str = "#### Grammar\n\n```text\nsource = identifier EOF ;\n```\n";
    const GRAMMAR: &str = "Source = 'identifier' 'EOF'\n";
    const MAP: &str = "source\tSource\n";
    const IDS: &str = "special:ERROR\t0\ntoken:identifier\t1\ntoken:EOF\t2\nnode:Source\t3\ntrivia:WHITESPACE\t4\ntrivia:NEWLINE\t5\ntrivia:LINE_COMMENT\t6\ntrivia:BLOCK_COMMENT\t7\nspecial:TOMBSTONE\t8\ntoken:@\t9\nspecial:ERROR_TOKEN\t10\nspecial:MISSING\t11\n";
    const LEXICAL: &str = "trivia:WHITESPACE\ntrivia:NEWLINE\ntrivia:LINE_COMMENT\ntrivia:BLOCK_COMMENT\nspecial:TOMBSTONE\ntoken:@\nspecial:ERROR_TOKEN\nspecial:MISSING\n";

    fn inputs<'a>(map: &'a str, ids: &'a str) -> Inputs<'a> {
        Inputs {
            grammar: GRAMMAR,
            production_map: map,
            kind_ids: ids,
            lexical_kinds: LEXICAL,
            language_spec: SPEC,
        }
    }

    fn formal_rule(document: &str, name: &str) -> String {
        let mut lines = document.lines().skip_while(|line| !line.starts_with(name));
        let first = lines
            .next()
            .unwrap_or_else(|| panic!("missing formal rule `{name}`"));
        std::iter::once(first)
            .chain(lines.take_while(|line| line.starts_with(' ')))
            .flat_map(str::split_whitespace)
            .collect::<Vec<_>>()
            .join(" ")
    }

    #[test]
    fn formal_grammar_copies_and_mechanical_rules_stay_in_sync() {
        let specification = include_str!("../../docs/language-spec.md");
        let agent_reference = include_str!("../../docs/agents/reference/allen-language.md");
        for rule in [
            "generic-parameters",
            "tuple-type",
            "function-type",
            "primary",
        ] {
            assert_eq!(
                formal_rule(agent_reference, rule),
                formal_rule(specification, rule),
                "formal grammar drift for {rule}"
            );
        }

        let grammar = include_str!("grammar/allen-0.1.ungram");
        for production in [
            "GenericParameters = '<' GenericParameter (',' GenericParameter)* ','? '>'",
            "TupleType = '(' (Type ',' (Type (',' Type)* ','?)?)? ')'",
            "FunctionType = 'fn' '(' (parameter_types:Type (',' parameter_types:Type)* ','?)? ')' 'returns' return_type:Type EffectClause?",
            "Primary = Literal | TemplateLiteral | 'identifier' | 'map' | 'Some' | 'Ok' | 'Err'",
        ] {
            assert!(
                grammar.contains(production),
                "mechanical grammar drift for `{production}`"
            );
        }
    }

    #[test]
    fn rendering_is_deterministic() {
        let first = render(&inputs(MAP, IDS)).unwrap();
        let second = render(&inputs(MAP, IDS)).unwrap();
        assert_eq!(first.kinds, second.kinds);
        assert_eq!(first.ast, second.ast);
        assert_eq!(first.inventory, second.inventory);
        assert!(first.kinds.starts_with(MARKER));
        assert!(first.ast.starts_with(MARKER));
        assert!(first.inventory.starts_with(MARKER));
        assert_eq!(first.files().len(), 3);
        assert!(first.ast.contains("pub fn ident_token(&self)"));
        assert!(first.ast.contains("pub fn eof_token(&self)"));
        assert!(
            first.inventory.contains(
                "(\"Source\", \"ident_token\", \"token:identifier\", \"required\", \"\")"
            )
        );
    }

    #[test]
    fn typed_ast_model_covers_every_wrapper_and_direct_relationship_once() {
        let grammar = include_str!("grammar/allen-0.1.ungram")
            .parse::<Grammar>()
            .unwrap();
        let model = typed_ast_model(&grammar).unwrap();
        assert_eq!(model.len(), 66);
        assert_eq!(
            model.iter().map(|node| node.accessors.len()).sum::<usize>(),
            392
        );

        let source = model
            .iter()
            .find(|node| grammar[node.node].name == "Source")
            .unwrap();
        assert_accessor(
            &grammar,
            source,
            "inline_manifest",
            "node:InlineManifest",
            Cardinality::Optional,
        );
        assert_accessor(
            &grammar,
            source,
            "import_declarations",
            "node:ImportDeclaration",
            Cardinality::Many,
        );
        assert_accessor(
            &grammar,
            source,
            "eof_token",
            "token:EOF",
            Cardinality::Required,
        );

        let function = model
            .iter()
            .find(|node| grammar[node.node].name == "FunctionDeclaration")
            .unwrap();
        assert_accessor(&grammar, function, "ty", "node:Type", Cardinality::Required);
        assert_accessor(
            &grammar,
            function,
            "effect_clause",
            "node:EffectClause",
            Cardinality::Optional,
        );
    }

    fn assert_accessor(
        grammar: &Grammar,
        node: &TypedNode,
        method: &str,
        target: &str,
        cardinality: Cardinality,
    ) {
        let accessor = node
            .accessors
            .iter()
            .find(|accessor| accessor.method == method)
            .unwrap();
        assert_eq!(accessor.target.inventory_name(grammar), target);
        assert_eq!(accessor.cardinality, cardinality);
    }

    #[test]
    fn typed_ast_model_rejects_public_accessor_name_collisions() {
        let grammar = "Source = Type | Ty\nType = 'identifier'\nTy = 'identifier'\n"
            .parse::<Grammar>()
            .unwrap();
        assert!(
            typed_ast_model(&grammar)
                .unwrap_err()
                .contains("typed AST accessor collision")
        );
    }

    #[test]
    fn synthetic_labels_preserve_roles_and_cardinality() {
        let grammar = "Source = first:'identifier' second:'identifier'? items:'string-literal' (items:'string-literal')* 'EOF'\n"
            .parse::<Grammar>()
            .unwrap();
        let model = typed_ast_model(&grammar).unwrap();
        let source = &model[0];
        assert_accessor_label(
            &grammar,
            source,
            "first_token",
            "token:identifier",
            Cardinality::Required,
            "first",
        );
        assert_accessor_label(
            &grammar,
            source,
            "second_token",
            "token:identifier",
            Cardinality::Optional,
            "second",
        );
        assert_accessor_label(
            &grammar,
            source,
            "items_tokens",
            "token:string-literal",
            Cardinality::Many,
            "items",
        );
        let rendered = render_ast(&grammar, &model);
        assert!(rendered.contains("const AST_PATTERN_SOURCE"));
        assert!(rendered.contains("pub fn first_token(&self) -> Option<SyntaxToken>"));
        assert!(
            rendered.contains("pub fn items_tokens(&self) -> impl Iterator<Item = SyntaxToken>")
        );
    }

    #[test]
    fn synthetic_overlapping_labeled_alternatives_generate_both_accessors() {
        let grammar = "Source = left:'identifier' | right:'identifier'\n"
            .parse::<Grammar>()
            .unwrap();
        let model = typed_ast_model(&grammar).unwrap();
        let source = &model[0];
        assert_accessor_label(
            &grammar,
            source,
            "left_token",
            "token:identifier",
            Cardinality::Optional,
            "left",
        );
        assert_accessor_label(
            &grammar,
            source,
            "right_token",
            "token:identifier",
            Cardinality::Optional,
            "right",
        );

        let rendered = render_ast(&grammar, &model);
        assert!(rendered.contains("pub fn left_token(&self) -> Option<SyntaxToken>"));
        assert!(rendered.contains("pub fn right_token(&self) -> Option<SyntaxToken>"));
    }

    #[test]
    fn rejects_observable_repetition_with_ambiguous_iteration_boundaries() {
        for source in [
            "Source = (items:'identifier' 'identifier' | items:'identifier')*\n",
            "Source = ('identifier' (items:'identifier' 'identifier' | items:'identifier'))*\n",
            "Source = (items:'identifier' 'identifier'?)*\n",
        ] {
            let grammar = source.parse::<Grammar>().unwrap();
            assert!(
                typed_ast_model(&grammar)
                    .unwrap_err()
                    .contains("typed AST repetition ambiguity on Source"),
                "accepted ambiguous grammar: {source}"
            );
        }
    }

    #[test]
    fn accepts_distinct_prefix_and_fixed_width_observable_repetitions() {
        for source in [
            "Source = (ident_items:'identifier' ',' | string_items:'string-literal')* 'EOF'\n",
            "Source = (items:'identifier' 'identifier' | items:'identifier' 'string-literal')* 'EOF'\n",
            "Source = ('identifier' items:',' | items:',')* 'EOF'\n",
            "Source = (left:'identifier' | right:'identifier')* 'EOF'\n",
            "Source = (('identifier')* ends:',')* 'EOF'\n",
        ] {
            let grammar = source.parse::<Grammar>().unwrap();
            typed_ast_model(&grammar)
                .unwrap_or_else(|error| panic!("rejected safe grammar `{source}`: {error}"));
        }
    }

    fn assert_accessor_label(
        grammar: &Grammar,
        node: &TypedNode,
        method: &str,
        target: &str,
        cardinality: Cardinality,
        label: &str,
    ) {
        let accessor = node
            .accessors
            .iter()
            .find(|accessor| accessor.method == method)
            .unwrap();
        assert_eq!(accessor.target.inventory_name(grammar), target);
        assert_eq!(accessor.cardinality, cardinality);
        assert_eq!(accessor.label.as_deref(), Some(label));
        assert!(matches!(accessor.selector, AccessorSelector::Label(_)));
    }

    #[test]
    fn checked_in_outputs_match_the_renderer() {
        let inputs = Inputs {
            grammar: include_str!("grammar/allen-0.1.ungram"),
            production_map: include_str!("grammar/production-map.tsv"),
            kind_ids: include_str!("grammar/kind-ids.tsv"),
            lexical_kinds: include_str!("grammar/lexical-kinds.tsv"),
            language_spec: include_str!("../../docs/language-spec.md"),
        };
        let generated = render(&inputs).unwrap();

        assert_eq!(
            include_bytes!("src/generated/kinds.rs"),
            generated.kinds.as_bytes()
        );
        assert_eq!(
            include_bytes!("src/generated/ast.rs"),
            generated.ast.as_bytes()
        );
        assert_eq!(
            include_bytes!("src/generated/inventory.rs"),
            generated.inventory.as_bytes()
        );
    }

    #[test]
    fn rejects_missing_or_orphan_productions() {
        assert!(
            render(&inputs("orphan\tSource\n", IDS))
                .unwrap_err()
                .contains("production map mismatch")
        );
    }

    #[test]
    fn rejects_duplicate_or_missing_kind_ids() {
        assert!(render(&inputs(MAP, "special:ERROR\t0\ntoken:identifier\t0\ntoken:EOF\t2\nnode:Source\t3\ntrivia:WHITESPACE\t4\ntrivia:NEWLINE\t5\ntrivia:LINE_COMMENT\t6\ntrivia:BLOCK_COMMENT\t7\nspecial:TOMBSTONE\t8\ntoken:@\t9\nspecial:ERROR_TOKEN\t10\nspecial:MISSING\t11\n")).unwrap_err().contains("duplicate"));
        assert!(render(&inputs(MAP, "special:ERROR\t0\ntoken:identifier\t1\nnode:Source\t3\ntrivia:WHITESPACE\t4\ntrivia:NEWLINE\t5\ntrivia:LINE_COMMENT\t6\ntrivia:BLOCK_COMMENT\t7\nspecial:TOMBSTONE\t8\ntoken:@\t9\nspecial:ERROR_TOKEN\t10\nspecial:MISSING\t11\n")).unwrap_err().contains("stable kind ID mismatch"));
    }
}
