[package]
name = "allen-http-get"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
flate2 = "=1.1.9"
httparse = "=1.10.1"
rustls = { version = "=0.23.42", default-features = false, features = ["ring", "std", "tls12"] }
url = "=2.5.8"
webpki-roots = "=1.0.9"

[lints]
workspace = true
